### PR TITLE
Support include at codegen time, and source-file at runtime.

### PR DESCRIPTION
**Pull request by chrhlnd**
So here is a codgen `include` and the runtime source-file. If you don't want the `source-file` in the base I suppose it could make some extension repo for this.

### CODE REVIEW

**Comment by glycerine** [comment]
@chrhlnd Hi Chris,

SourceExpressions() and LoadExpressions() seem really similar.

Likewise, SourceStream() and LoadStream() seem really similar.

Could not (source path) be defined in terms of LoadStream()?  

Why have such duplication?  There well could be a good reason, I'm just not familiar enough with the internals to understand.

Thanks,
Jason

**Comment by chrhlnd** [comment]
Well the Source versions generate a function and run it.. then discard the function. The Load versions generate a "main" function and set it in the environment. I did refactor the parsing part some so every version isn't duplicating that part.

**Comment by zhemao** [comment]
I think this code is fine. My one issue is that these features should not be enabled by default, since it makes it more difficult to sandbox the interpreter. The "source-file" function can be easily added as an optional extension. Take a look at what the existing "ImportEval" function does and you'll see how to accomplish this. As for making "include" statements an optional add-on, I'm less sure of how to accomplish that. Perhaps you could add a flag to the environment and the generator can read this flag to decide whether or not to switch on "include" generation.

**Comment by zhemao** [comment]
I think I can take care of making these optional myself.

**Comment by zhemao** [comment]
Rebased and merged

**Comment by chrhlnd** [comment]
Ok thanks.. I don't get much time during the week.

**Pull request closed without merging**
