### PR TITLE
Support closure on (fn)

### PR DESCRIPTION
**Pull request by chrhlnd**
Ok I took a stab at this, the original script runs now, also (def val (fn [] (blah)) works as a callable too.

1st commit is the meat of the real change, 2nd commit is go fmt on everything.

### CODE REVIEW

**Comment by zhemao** [comment]
Hmm, I think cloning the entire environment might be a little too heavyweight. The only thing that needs to be switched out is the scope stack. Now that I think about it, I think the way I designed scoping was a bit incorrect. The parent scope of a function's top-level scope should be the global scope (or the scope of the function it was defined in, in the case of closures). When the function is defined, an object saving its enclosing scope hierarchy should be placed on the stack. For regular functions, this object could just be null or empty. When the function is called, the current scope hierarchy should be saved (on a stack of scope stacks), and the one for the function should be popped off the argument stack. A new scope is then added for the called function and the execution should continue from the beginning of the function bytecode. Do you think you could implement it that way? Otherwise, I'll take a stab at it when I have time.

**Comment by chrhlnd** [comment]
Hmm well the references to data would have to be preserved too. The 'fun' parameter being used in the closure defined in filter (being passed to foldl), is referencing the data from the filter call but its execution won't necessarily be in the current stack. It is in this case; but the 'fn' value could be returned and passed around, then applied at some other point.

**Comment by zhemao** [comment]
You're right. In that case, we should bundle the scope stack reference into the function object.

**Comment by chrhlnd** [comment]
Another option might be, to scan the generated instructions, resolve all "gets" in the current frame, save the value in a list, put the list where I put the environment pointer, on execution, push these on the data stack.

**Comment by chrhlnd** [comment]
One more cleanup, to avoid capturing globals needlessly.

**Comment by zhemao** [comment]
Looks good. I added some additional tests and merged into master. Thanks for your help.

**Pull request merged**
